id: P0F67777F
initial_creation_type: input
source_metadata:
  title: Striking the Vital Point in Three Statements
  language: pt
  description: 'A series of texts based on the final testament of Garab Dorje, a key
    Dzogchen instruction known as ''Striking the Vital Point in Three Statements''
    (tshig gsum gnad brdegs):'
  volume:
    1ffa42a2ab3e4856abb941c8c4496acb:
      title: Pith Instruction on the Three Crucial Statements
      parent: Advice
    0d78127136804ba5b8d8be137f20f2df:
      title: The Three Statements that Strike the Vital Point
      parent: Root Text
    b8a43baaf44a4be4a2234e33f7f08d87:
      title: Summary of Striking the Vital Point in Three Statements
      parent: Summary
    ee2110a831dc4cd792e157dc58cfac84:
      title: The Special Teaching of the Wise and Glorious King – Commentary
      parent: Special Teaching of the Wise and Glorious King
    b829fc242b9e4aefb0689b0bc5036e9c:
      title: The Special Teaching of the Wise and Glorious King—Root Text
      parent: Special Teaching of the Wise and Glorious King
    3349938739524b45ba2eb2ab4beb35d5:
      title: The Special Teaching of the Wise and Glorious King—Root Text (arranged
        in Tibetan-English verses)
      parent: Special Teaching of the Wise and Glorious King
    1f2b552e00fc4754a1536d3570f7caef:
      title: Annotation Commentary on the Special Teaching of the Wise and Glorious
        King
      parent: Special Teaching of the Wise and Glorious King
created_at: '2022-03-01T05:58:24.344066'
last_modified_at: '2022-03-01T05:58:24.344068'
